### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by giangdao1402** [mttgdd/open-radvlad#1]
Hi @mttgdd 
Thank for your great work
I wonder if you can provide training code so i can replicate your excellent work
Thank you !

**Comment by mttgdd** [comment]
Hello, thanks for your interest in this. The only "training" step is finding cluster centres, I provide this code at https://github.com/mttgdd/open-radvlad/blob/main/src/cluster.py. This is e.g. used in https://github.com/mttgdd/open-radvlad/blob/8238482761a34511934f6af7b85cb69729fdcb69/launch/fft_vlad.py#L34
